// Import fonts for the website
import { Geist, Geist_Mono } from "next/font/google";
// Import basic styling
import "./globals.css";
import Navbar from '@/components/Navbar';

// Create a variable to reference later in CSS and choose basic Latin alphabet
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Set up the page title that appears in the browser tab
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Primary wrapper that defines the layout
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        className={geistSans.className}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}

